# Use root/example as user/password credentials
version: '3.9'

services:

  db:
    container_name: MariaDb
    image: mariadb:latest   
    restart: always
    environment:
      SERVER: localhost
      USER: root
      MARIADB_ROOT_PASSWORD: 12345  
      DATABASE: DataUser
    ports: 
    - "3306:3306"  